# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# conda install mkdocs-material mkdocs-jupyter mkdocstrings mkdocstrings-python -c conda-forge
site_name: ipcoal documentation
repo_url: https://github.com/eaton-lab/ipcoal
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    primary: blue grey
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy  # unfortunately style varies depending if mkdocs-jupyter or not.
    # - search.highlight
    # - search.suggest

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           # docstring_style: google
  #           docstring_style: numpy
  #           annotations_path: brief            
  - mkdocs-jupyter:
      kernel_name: py310
      ignore_h1_titles: true
      include_requirejs: true
      # highlight_extra_classes: "custom-css-classes"  # don't use this!
      # execute: True      
      # no_input: True
      # show_input: False
      # include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
      ignore: [".ipynb_checkpoints/*.ipynb"]

extra_css:
  # - stylesheets/extra.css
  - css/mkdocstrings.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md    
  - Getting started:
    - Installation: installation.md
    # - Change log: change_log.md
    - Contribute: contribute.md
    - Citation: citation.md

  - User Guide:
    - Quick Guide: quicker_guide.ipynb
    - Terminology and Units: terminology.md
    # - Coalescent theory:
    #     - Kingman coalescent: theory_kingman.ipynb
    #     - Multispecies coalescent: theory_msc.ipynb
        # - Network coalescent: ...
    # - Simulation: 
    - Model class: Model_class.ipynb
    - Simulation and TreeSequences: simulation.ipynb
    # - Interaction with <i>tskit</i>: intertskit_integration.ipynb
    # - Demography and Species Trees: demography.ipynb
    # - Substitution Models: substitution.ipynb
    # - Recomb and Mut Maps: recomb_mut_maps.ipynb
    - Phylogenetic inference:
      - Gene tree inference: infer_gene_trees.ipynb
      - Species tree inference: infer_species_trees.ipynb
      - Species network inference: infer_species_network.ipynb
    - Visualizations: visualization.ipynb
    - Likelihoods: 
      - MSC likelihood: MSC_likelihood.ipynb
      - SMC likelihood: SMC_likelihood.ipynb
    # - Writing data: writing.ipynb
  
  - FAQs: FAQs.md

  # Use this for the gallery: https://smarie.github.io/mkdocs-gallery/
  - Cookbooks/Examples:
    - 1. Species tree inference: example-Astral.ipynb
    - 2. Network inference: example-SNaQ.ipynb
    - 3. Linked genealogies: example-Twist.ipynb
    - 4. Generation time variation (theory): cookbooks/cookbook-gentime-theory.ipynb    
    - 5. Generation time variation (empirical): cookbooks/cookbook-gentime-empirical.ipynb
    # - Single population coalescent: example-Kingman.ipynb
    # - Multispecies coalescent: example-MSC.ipynb

  # - Source:
  #   - Data structures: 
  #     - class - ToyTree: source/toytree.md
  #     - class - Node: source/node.md
  #     - class - MultiTree: source/multitree.md
  #   - Modules:
  #     - io:
  #       - tree: source/treeio.md
  #       - write: source/write.md
  #     - distance: 
  #       - treedist: source/distance.md
  #       - nodedist: source/distance.md        

  # - Blog: blog.md


# markdown_extensions:

#   # Python Markdown
#   - abbr
#   - admonition
#   - attr_list
#   - def_list
#   - footnotes
#   - meta
#   - tables
#   - md_in_html
#   - toc:
#       permalink: true

#   # Python Markdown Extensions
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
#   - pymdownx.highlight
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.snippets
#   - pymdownx.tabbed:
#       alternate_style: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde

# plugins:
  # - search
    # - navigation.sections  # expands sections in nav.
  # markdown_extensions:
  #   - pymdownx.highlight:
  #       use_pygments: true
  #   - pymdownx.superfences
