package:
  name: ipcoal
  version: '0.1.1'

source:
  url: https://github.com/eaton-lab/ipcoal/archive/0.1.1.tar.gz
  sha256: ee2e45d77a07a61be2e61543f9526df5fb1bb3850bd4e471fd9ba7b7bcf9fdf5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.10
    - scipy >=0.10
    - pandas >=0.16
    - numba
    - toytree >=1.0.9
    - future
    - msprime
    - raxml
    - seq-gen
    - mrbayes

test:
  imports:
    - ipcoal

about:
  home: http://github.com/eaton-lab/ipcoal
  license: GPLv3
  summary: Interactive and reproducible simulation and analysis of gene trees.
