package:
  name: ipcoal
  version: '0.1.2'

source:
  url: https://github.com/eaton-lab/ipcoal/archive/0.1.2.tar.gz
  sha256: 68b9474c9b0e34ee6efe3106ffd508d1614b8c96ec648987b43bae5cc0a6acbb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - pandas
    - numba
    - toytree >=1.1.4
    - future
    - msprime
    - raxml
    - tabix
    # - seq-gen
    # - mrbayes

test:
  imports:
    - ipcoal

about:
  home: http://github.com/eaton-lab/ipcoal
  license: GPLv3
  summary: Interactive and reproducible simulation and analysis of gene trees.
