package:
  name: ipcoal
  version: '0.1.3'

source:
  url: https://github.com/eaton-lab/ipcoal/archive/0.1.3.tar.gz
  sha256: cf0de4295cefd0628dacd41e571096db42ca5ffa08e76546bc3df30d70836987

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - pandas
    - numba
    - toytree >=1.1.4
    - future
    - msprime
    - raxml
    - tabix
    # - seq-gen
    # - mrbayes

test:
  imports:
    - ipcoal

about:
  home: http://github.com/eaton-lab/ipcoal
  license: GPLv3
  summary: Interactive and reproducible simulation and analysis of gene trees.
